# ===============================
# APPLICATION
# ===============================
spring.application.name=GarageFlow

# ===============================
# SERVER PORT
# ===============================
server.port=${PORT:8080}

# ===============================
# H2 DATABASE (LOCAL / SIMPLE DEPLOY)
# ===============================
spring.datasource.url=jdbc:h2:file:./data/garageflow
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# H2 CONSOLE (DEV ONLY)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console